version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  env_file:
  - ./.env.dev
  volumes:
  - ./log:/app/log
  - ./app:/app

 mysqldb:
  image: mysql
  ports:
  - 3307:3306
  env_file:
  - ./.env.db
  volumes:
  - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  initdb.d: