version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 5000:5000
  volumes:
  - ./app:/app

 mysqldb:
  image: mysql
  ports:
  - 3307:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - ./initdb.d:/docker-entrypoint-initdb.d

volumes:
  initdb.d: